apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  labels:
    app: frontend
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: blue
  template:
    metadata:
      labels:
        app: frontend
        version: blue
    spec:
      containers:
      - name: frontend
        image: pavan28/featured-stories-frontend:latest
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  labels:
    app: backend
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
      - name: backend
        image: pavan28/featured-stories-backend:latest
        env:
        - name: CONFIG_PATH
          value: /usr/src/app/config.env
        ports:
        - containerPort: 8000


#  env:
#         - name: MONGO_URI
#           value: "mongodb+srv://pavankmjp:QJOiJOSoXFe2SMd0@cluster1.wsxgh5u.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"
#         - name: PORT
#           value: "8000"
#         - name: MONGO_URI_DEV
#           value: "mongodb://localhost:27017/FeaturedStories"