apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
    version: green # Change this to blue to switch traffic to the blue deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
    version: green # Change this to blue to switch traffic to the blue deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
